ISSUE_NORMALIZER = {
    "dent": "dent",
    "dented": "dent",
    "dents": "dent",
    "scratch": "scratch",
    "scratches": "scratch",
    "scratched": "scratch",
    "scrape": "scratch",
    "crack": "crack",
    "cracked": "crack",
    "cracks": "crack",
    "shatter": "glass_shatter",
    "shattered": "glass_shatter",
    "broken": "broken_part",
    "broke": "broken_part",
    "break": "broken_part",
    "missing": "missing_part",
    "gone": "missing_part",
    "torn": "torn_packaging",
    "tear": "torn_packaging",
    "ripped": "torn_packaging",
    "ripped open": "torn_packaging",
    "crushed": "crushed_packaging",
    "crush": "crushed_packaging",
    "water": "water_damage",
    "water damage": "water_damage",
    "water damaged": "water_damage",
    "wet": "water_damage",
    "moisture": "water_damage",
    "stain": "stain",
    "stained": "stain",
    "stains": "stain",
    "sticky": "stain",
    "mark": "scratch",
    "marks": "scratch",
    "scuffed": "scratch",
    "scuff": "scratch",
    "ding": "dent",
    "dings": "dent",
    "hail": "dent",
    "chipped": "broken_part",
    "chip": "broken_part",
    "smashed": "broken_part",
    "glass crack": "glass_shatter",
    "glass broken": "glass_shatter",
    "paint": "scratch",
    "paint damage": "scratch",
    "crease": "crushed_packaging",
    "creasing": "crushed_packaging",
    "crushed box": "crushed_packaging",
    "crushed package": "crushed_packaging",
    "badly crushed": "crushed_packaging",
    "torn packaging": "torn_packaging",
    "torn seal": "torn_packaging",
    "torn open": "torn_packaging",
    "opened": "torn_packaging",
    "shattered windshield": "glass_shatter",
    "shattered screen": "glass_shatter",
    "front glass": "glass_shatter",
    "display crack": "crack",
    "display broken": "broken_part",
    "won't open": "broken_part",
    "not opening": "broken_part",
    "won't turn on": "broken_part",
    "not working": "broken_part",
    "malfunction": "broken_part",
    "defective": "broken_part",
    "faulty": "broken_part",
    "no damage": "none",
    "nothing": "none",
    "fine": "none",
    "ok": "none",
    "unclear": "unknown",
    "not sure": "unknown",
    "unknown": "unknown",
}

PART_NORMALIZER = {
    "front bumper": "front_bumper",
    "bumper front": "front_bumper",
    "front": "front_bumper",
    "rear bumper": "rear_bumper",
    "back bumper": "rear_bumper",
    "back": "rear_bumper",
    "bumper rear": "rear_bumper",
    "bumper": "unknown",
    "door": "door",
    "door panel": "door",
    "side door": "door",
    "hood": "hood",
    "bonnet": "hood",
    "top panel": "hood",
    "windshield": "windshield",
    "windscreen": "windshield",
    "front glass": "windshield",
    "front window": "windshield",
    "side mirror": "side_mirror",
    "wing mirror": "side_mirror",
    "mirror": "side_mirror",
    "headlight": "headlight",
    "headlamp": "headlight",
    "head light": "headlight",
    "front light": "headlight",
    "taillight": "taillight",
    "tail light": "taillight",
    "back light": "taillight",
    "rear light": "taillight",
    "fender": "fender",
    "quarter panel": "quarter_panel",
    "quarter": "quarter_panel",
    "body": "body",
    "car body": "body",
    "screen": "screen",
    "display": "screen",
    "monitor": "screen",
    "keyboard": "keyboard",
    "keys": "keyboard",
    "trackpad": "trackpad",
    "touchpad": "trackpad",
    "pad": "trackpad",
    "hinge": "hinge",
    "lid": "lid",
    "cover": "lid",
    "corner": "corner",
    "laptop corner": "corner",
    "port": "port",
    "usb": "port",
    "base": "base",
    "bottom": "base",
    "laptop body": "body",
    "box": "box",
    "package": "box",
    "package box": "box",
    "shipping box": "box",
    "delivery box": "box",
    "outside box": "box",
    "package corner": "package_corner",
    "box corner": "package_corner",
    "package side": "package_side",
    "surface": "package_side",
    "package surface": "package_side",
    "seal": "seal",
    "tape": "seal",
    "seal area": "seal",
    "label": "label",
    "contents": "contents",
    "inside": "contents",
    "item inside": "contents",
    "product inside": "contents",
    "product": "item",
    "item": "item",
}


def normalize_issue(raw_issue):
    raw = raw_issue.lower().strip().rstrip(".")
    return ISSUE_NORMALIZER.get(raw, "unknown")


def normalize_part(raw_part):
    raw = raw_part.lower().strip().rstrip(".")
    return PART_NORMALIZER.get(raw, "unknown")
